# Multistage Dockerfile

# ------Stage 1-------

FROM python:3.9 AS builder

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y gcc default-libmysqlclient-dev pkg-config \
	&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install mysqlclient \
	&& pip install --no-cache-dir -r requirements.txt


# -----Stage 2-----


FROM python:3.9-slim

WORKDIR /app

RUN apt-get update

COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

COPY . .


ENTRYPOINT ["python"]

CMD ["app.py"]

